service: edge-lambda
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 5
plugins:
  - serverless-prune-plugin
  - serverless-offline
environment:
  KEY: J/PYjc1ftDFK5+77U1PB80v2TamokGap5yCIP2YI6tQ=
functions:
  lambdaEdge:
    name: aws-lambda-service
    handler: app.handler
    description: demo aws lambda function
    role: LambdaEdgeRole
resources:
  Resources:
    LambdaEdgeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: lambda-edge-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole